@startuml
    title Filtering products by a category
    skinparam style strictuml


    actor Customer as cust
    box "Web Broswer" #white
    participant "view-products.html" as vp_html <<HTML Page>>
    participant "view-products.js" as vp_js <<Vue Controller>>
    participant "axios" as ax <<HTTP Middleware>>
    end box
    box "Web Server" #white
    participant "Server" as sr <<Jooby Server>>
    participant "ProductModule" as PM <<Jooby Module>>
    participant "ProductJdbiDAO" as dao <<DAO>>
    end box
    database Database as db


    cust -> vp_html: Click category to view
    activate vp_html

    vp_html -> vp_js: filterProducts(category)
    activate vp_js

    vp_js -> ax: get("/api/categories/category")
    activate ax

    ax -> sr: HTTP GET /api/categories/category
    activate sr

    sr -> PM: get("/api/categories/category")
    activate PM

    PM -> dao: filterByCategory(category)
    activate dao
    
    dao -> db: SELECT * FROM PRODUCT WHERE CATEGORY = :category
    activate db
    
    db --> dao: result
    deactivate db

    dao --> PM: filtered products
    deactivate dao

    PM --> sr: products
    deactivate PM

    sr --> ax: Products JSON
    deactivate sr

    ax --> vp_js: JavaScript products
    deactivate ax

    vp_js -> vp_js: Update products stored

    vp_js --> vp_html: Update products shown
    deactivate vp_js

    vp_html -> vp_html: Display products

@enduml